extends:
 - stylelint-config-standard
 - stylelint-config-prettier

rules:
    # Until https://github.com/stylelint/stylelint/issues/2489 and
    # https://github.com/stylelint/stylelint/issues/3196 are resolved
    # stylelint's no-descending-specificity rule throws too many false
    # positives to be worthwhile:
    no-descending-specificity: null
